services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: http://57.128.249.133:9341
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://57.128.249.133:9341
    restart: unless-stopped
    container_name: car-service-frontend
